<script setup lang="ts">
import Icon from '../Icon.vue'
import { computed, onBeforeUnmount, reactive, ref } from 'vue'
import { onBeforeRouteLeave, onBeforeRouteUpdate } from 'vue-router'
import { useSettingsScope } from '../settingsScope'
const { request:api }=useSettingsScope()
import { t,formatDate } from '../../i18n'
import { testingEditable,testTone,type TestDesign,type TestPoint,type TestWorkspace,type TestCaseRecord } from '../../testingWorkspace'
import AppSelect from '../AppSelect.vue'
import RequirementPicker,{type RequirementChoice} from '../RequirementPicker.vue'
import MemberMultiSelect from '../MemberMultiSelect.vue'
import ResizableDrawer from '../ResizableDrawer.vue'
const props=defineProps<{workspace:TestWorkspace;members:any[]}>(),emit=defineEmits<{refresh:[]}>()
const q=ref(''),mine=ref(''),opened=ref(false),saving=ref(false),error=ref(''),width=ref(1160),record=ref<TestDesign|null>(null)
const requirement=ref<RequirementChoice|null>(null),baseline=ref(''),loading=ref(false)
const fresh=()=>({name:'',description:'',requirementId:null as number|null,ownerUserId:'',tags:'',points:[] as TestPoint[]})
const edit=reactive(fresh())
const dirty=computed(()=>opened.value&&JSON.stringify(edit)!==baseline.value)
const designs=computed(()=>props.workspace.designs.filter(x=>(!q.value||`${x.name} ${x.tags} ${x.description}`.toLowerCase().includes(q.value.trim().toLowerCase()))&&(!mine.value||x.ownerUserId===mine.value)))
const uniqueCases=(item:TestDesign)=>new Set(item.points.flatMap(x=>x.caseIds)).size
function canLeave(){return !saving.value&&(!dirty.value||window.confirm(t('测试设计尚未保存，确定放弃修改吗？')))}
onBeforeRouteLeave(canLeave);onBeforeRouteUpdate((to,from)=>to.query.tab===from.query.tab||canLeave())
function unload(event:BeforeUnloadEvent){if(dirty.value||saving.value){event.preventDefault();event.returnValue=''}}
window.addEventListener('beforeunload',unload);onBeforeUnmount(()=>{version++;window.removeEventListener('beforeunload',unload)})
let version=0
async function open(item:TestDesign|null){
 if(!canLeave())return;error.value='';opened.value=true;record.value=item;Object.assign(edit,testingEditable(fresh(),item?JSON.parse(JSON.stringify(item)):null));baseline.value=JSON.stringify(edit);requirement.value=null
 const sequence=++version
 if(item?.requirementId)try{const found=await api<RequirementChoice>(`/requirements/${item.requirementId}`);if(sequence===version)requirement.value=found}catch(cause){if(sequence===version)error.value=cause instanceof Error?cause.message:'需求读取失败'}
}
function close(){if(!canLeave())return;version++;opened.value=false}
function addPoint(){edit.points.push({title:'',category:'正常路径',priority:'P1',caseIds:[]})}
function movePoint(index:number,direction:number){const target=index+direction;if(target<0||target>=edit.points.length)return;const point=edit.points.splice(index,1)[0]!;edit.points.splice(target,0,point)}
async function save(){if(!props.workspace.canEdit||saving.value)return;saving.value=true;error.value='';try{const result=await api<TestDesign>(`/testing/designs${record.value?'/'+record.value.id:''}`,{method:record.value?'PATCH':'POST',body:JSON.stringify(edit)});Object.assign(edit,testingEditable(fresh(),result));record.value=result;baseline.value=JSON.stringify(edit);opened.value=false;emit('refresh')}catch(cause){error.value=cause instanceof Error?cause.message:'保存失败，请重试'}finally{saving.value=false}}
async function remove(item:TestDesign){if(!props.workspace.canManage||!window.confirm(t('删除测试设计“{name}”？已关联的用例将保留。',{name:item.name})))return;saving.value=true;try{await api(`/testing/designs/${item.id}`,{method:'DELETE'});emit('refresh')}catch(cause){error.value=cause instanceof Error?cause.message:'删除失败'}finally{saving.value=false}}
const linkingIndex=ref<number|null>(null),caseQuery=ref(''),candidates=ref<TestCaseRecord[]>([]),linkIds=ref<number[]>([]),linkPage=ref(1),linkTotal=ref(0)
let searchVersion=0
async function searchCases(){const sequence=++searchVersion;loading.value=true;try{const result=await api<{items:TestCaseRecord[];total:number}>('/test-cases?'+new URLSearchParams({q:caseQuery.value,page:String(linkPage.value),pageSize:'20'}));if(sequence===searchVersion){candidates.value=result.items;linkTotal.value=result.total}}catch(cause){if(sequence===searchVersion)error.value=cause instanceof Error?cause.message:'用例读取失败'}finally{if(sequence===searchVersion)loading.value=false}}
function linkPoint(index:number){linkingIndex.value=index;linkIds.value=[...edit.points[index]!.caseIds];caseQuery.value='';linkPage.value=1;void searchCases()}
function toggleCase(id:number){linkIds.value=linkIds.value.includes(id)?linkIds.value.filter(x=>x!==id):[...linkIds.value,id]}
function closeLink(){if(saving.value)return;searchVersion++;loading.value=false;linkingIndex.value=null}
function finishLink(){if(linkingIndex.value!==null&&edit.points[linkingIndex.value])edit.points[linkingIndex.value]!.caseIds=[...linkIds.value];linkingIndex.value=null}
</script>

<template>
 <section class="test-designs">
  <header class="test-section-head"><div><h2>{{t('测试设计')}}</h2><p>{{t('先拆解需求与风险，再组织测试点并关联用例，保留清晰的覆盖关系。')}}</p></div><button class="btn primary" :disabled="!workspace.canEdit||saving" @click="open(null)">＋ {{t('创建测试设计')}}</button></header>
  <p v-if="error&&!opened" class="test-notice error" role="alert">{{t(error)}}</p>
  <div class="test-filter-row"><label class="test-search"><Icon name="search"/><input v-model="q" :aria-label="t('搜索测试设计')" :placeholder="t('搜索设计名称、标签或说明')"></label><AppSelect v-model="mine" :label="t('设计负责人')" :options="[{value:'',label:t('所有负责人')},...members.filter(x=>x.active).map(x=>({value:x.id,label:x.name}))]"/><span class="test-muted">{{t('共 {count} 条',{count:designs.length})}}</span></div>
  <div class="test-table-wrap"><table class="test-table"><thead><tr><th>{{t('测试设计名称')}}</th><th>{{t('关联需求')}}</th><th>{{t('负责人')}}</th><th>{{t('测试点')}}</th><th>{{t('关联用例')}}</th><th>{{t('更新时间')}}</th><th/></tr></thead><tbody><tr v-for="item in designs" :key="item.id"><td class="test-title-cell"><button class="test-text-button" @click="open(item)">{{item.name}}</button><small>{{item.tags||'—'}}</small></td><td><router-link v-if="item.requirementId" :to="`/requirements?req=${item.requirementId}`">REQ-{{String(item.requirementId).padStart(4,'0')}}</router-link><span v-else>—</span></td><td>{{members.find(x=>x.id===item.ownerUserId)?.name||'—'}}</td><td>{{item.points.length}}</td><td>{{uniqueCases(item)}}</td><td>{{formatDate(item.updatedAt)}}</td><td><button v-if="workspace.canManage" class="test-text-button danger" :disabled="saving" @click="remove(item)">{{t('删除')}}</button></td></tr><tr v-if="!designs.length"><td colspan="7" class="test-empty-cell"><h3>{{t('从一个需求开始测试设计')}}</h3><p>{{t('梳理正常流程、边界、异常和权限场景，为每个测试点关联可执行用例。')}}</p><button class="btn" :disabled="!workspace.canEdit" @click="open(null)">＋ {{t('创建测试设计')}}</button></td></tr></tbody></table></div>
  <div v-if="opened" class="drawer-shade" @click.self="close"><ResizableDrawer v-model:width="width" storage-key="testing.design.width" :initial-width="1160" :min-width="700" :label="record?.name||t('创建测试设计')" class="test-design-drawer"><header class="test-drawer-header"><div><span class="test-breadcrumb">{{t('需求 → 测试点 → 测试用例')}}</span><h2>{{record?.name||t('创建测试设计')}}</h2></div><button class="test-icon-button" :aria-label="t('关闭')" :disabled="saving" @click="close">×</button></header><form class="test-scroll-form" @submit.prevent="save"><div class="test-detail-content"><p v-if="error" class="test-notice error" role="alert">{{t(error)}}</p><fieldset class="test-fieldset" :disabled="saving||!workspace.canEdit"><label class="test-field">{{t('设计名称')}} *<input v-model="edit.name" maxlength="200" required :placeholder="t('例如：账号权限与数据隔离测试设计')"></label><div class="test-two-columns"><RequirementPicker v-model="edit.requirementId" :selected-requirement="requirement" :label="t('关联需求')" :disabled="saving||!workspace.canEdit" @change="requirement=$event"/><MemberMultiSelect single :label="t('设计负责人')" :model-value="edit.ownerUserId?[edit.ownerUserId]:[]" :members="members" :disabled="saving||!workspace.canEdit" :show-lead="false" @update:model-value="edit.ownerUserId=$event[0]||''"/></div><label class="test-field">{{t('设计说明')}}<textarea v-model="edit.description" rows="3" maxlength="20000" :placeholder="t('说明业务范围、测试策略、依赖与主要风险')"/></label><label class="test-field">{{t('标签')}}<input v-model="edit.tags" maxlength="500" :placeholder="t('用逗号分隔标签')"></label><div class="test-section-title"><h3>{{t('测试点')}}</h3><button type="button" class="btn" @click="addPoint">＋ {{t('添加测试点')}}</button></div>
   <div v-if="!edit.points.length" class="test-empty-cell">{{t('添加测试点，将业务场景拆成可验证的目标。')}}</div>
   <article v-for="(point,index) in edit.points" :key="index" class="test-point-card"><header><span class="test-step-index">{{index+1}}</span><input v-model="point.title" :aria-label="t('测试点标题')+' '+(index+1)" required maxlength="200" :placeholder="t('写出需要验证的行为或规则')"><div class="test-step-actions"><button type="button" :aria-label="t('上移测试点')" :disabled="index===0" @click="movePoint(index,-1)">↑</button><button type="button" :aria-label="t('下移测试点')" :disabled="index===edit.points.length-1" @click="movePoint(index,1)">↓</button><button type="button" :aria-label="t('删除测试点')" @click="edit.points.splice(index,1)">×</button></div></header><footer><AppSelect v-model="point.category" :label="t('覆盖场景')" :disabled="saving||!workspace.canEdit" :options="[...new Set(['正常路径','边界条件','异常场景','权限安全','兼容性','性能',point.category])].map(value=>({value,label:t(value)}))"/><AppSelect v-model="point.priority" :label="t('等级')" :disabled="saving||!workspace.canEdit" :options="['P0','P1','P2','P3'].map(value=>({value,label:value}))"/><div class="test-linked-cases"><router-link v-for="id in point.caseIds" :key="id" :to="`/tests?tab=cases&case=${id}`">TC-{{String(id).padStart(4,'0')}}</router-link></div><button type="button" class="btn" @click="linkPoint(index)">{{t('关联用例')}} <span>{{point.caseIds.length}}</span></button></footer></article>
  </fieldset></div><footer class="test-editor-footer"><span class="test-muted">{{dirty?t('有未保存的修改'):t('内容已同步')}}</span><div><button type="button" class="btn" :disabled="saving" @click="close">{{t('取消')}}</button><button class="btn primary" :disabled="saving||!workspace.canEdit">{{saving?t('保存中…'):t('保存测试设计')}}</button></div></footer></form></ResizableDrawer></div>
  <div v-if="linkingIndex!==null" class="test-modal-shade" @click.self="closeLink"><section class="test-modal wide" role="dialog" aria-modal="true" :aria-label="t('关联测试用例')"><header><h2>{{t('关联测试用例')}}</h2><button class="test-icon-button" :aria-label="t('关闭')" @click="closeLink">×</button></header><div class="test-modal-body"><form class="test-filter-row" @submit.prevent="linkPage=1;searchCases()"><input v-model="caseQuery" :aria-label="t('搜索用例')" :placeholder="t('搜索用例编号或标题')"><button class="btn">{{t('搜索')}}</button></form><p class="test-muted">{{t('已选 {count} 条',{count:linkIds.length})}}</p><div class="test-case-choices"><label v-for="item in candidates" :key="item.id"><input type="checkbox" :checked="linkIds.includes(item.id)" @change="toggleCase(item.id)"><span class="test-code">{{item.code}}</span><b>{{item.title}}</b><span :class="['test-badge',testTone(item.status)]">{{t(item.status)}}</span></label><p v-if="!candidates.length">{{loading?t('正在加载…'):t('暂无符合条件的用例')}}</p></div><div class="test-pagination"><span>{{t('共 {count} 条',{count:linkTotal})}}</span><div><button class="btn" :disabled="loading||linkPage<=1" @click="linkPage--;searchCases()">‹</button><span>{{linkPage}} / {{Math.max(1,Math.ceil(linkTotal/20))}}</span><button class="btn" :disabled="loading||linkPage*20>=linkTotal" @click="linkPage++;searchCases()">›</button></div></div></div><footer><button class="btn" @click="closeLink">{{t('取消')}}</button><button class="btn primary" @click="finishLink">{{t('确认关联')}}</button></footer></section></div>
 </section>
</template>
