<script setup lang="ts">
import { computed, ref } from 'vue'
import { t } from '../i18n'
type Field={key:string;label:string;group?:string;kind?:string;custom?:boolean;fixed?:boolean;default?:boolean}
const props=defineProps<{fields:Field[];modelValue:string[];disabled?:boolean;sortable?:boolean}>()
const emit=defineEmits<{(event:'update:modelValue',keys:string[]):void}>()
const query=ref(''),dragging=ref('')
const label=(field:Field)=>field.custom?field.label:t(field.label)
const category=(field:Field)=>field.custom?'自定义字段':field.group==='角色权重'?'角色权重':['person','date'].includes(field.kind||'')||['owner','assignee','createdAt','updatedAt','startDate','endDate'].includes(field.key)?'人员与时间':field.group||'基础信息'
const registry=computed(()=>new Map(props.fields.map(field=>[field.key,field])))
const selected=computed(()=>[...new Set([...props.fields.filter(field=>field.fixed).map(field=>field.key),...props.modelValue])].map(key=>registry.value.get(key)).filter(Boolean) as Field[])
const groups=computed(()=>{const all=new Map<string,Field[]>();for(const field of props.fields){if(!label(field).toLowerCase().includes(query.value.trim().toLowerCase())&&!field.key.toLowerCase().includes(query.value.trim().toLowerCase()))continue;const key=category(field);if(!all.has(key))all.set(key,[]);all.get(key)!.push(field)}return [...all].map(([name,fields])=>({name,fields}))})
function change(key:string,checked:boolean){if(props.disabled||registry.value.get(key)?.fixed||!registry.value.has(key))return;const keys=selected.value.map(field=>field.key);emit('update:modelValue',checked?[...new Set([...keys,key])]:keys.filter(value=>value!==key))}
function move(key:string,by:number){if(props.disabled||!props.sortable||registry.value.get(key)?.fixed)return;const keys=selected.value.map(field=>field.key),index=keys.indexOf(key),target=index+by;if(index<0||target<0||target>=keys.length||registry.value.get(keys[target]!)?.fixed)return;[keys[index],keys[target]]=[keys[target]!,keys[index]!];emit('update:modelValue',keys)}
function start(field:Field,event:DragEvent){if(props.disabled||!props.sortable||field.fixed){event.preventDefault();return}dragging.value=field.key;event.dataTransfer?.setData('text/plain',field.key);if(event.dataTransfer)event.dataTransfer.effectAllowed='move'}
function drop(key:string){const from=dragging.value;dragging.value='';if(props.disabled||!props.sortable||!from||from===key||registry.value.get(key)?.fixed||registry.value.get(from)?.fixed)return;const keys=selected.value.map(field=>field.key),a=keys.indexOf(from),b=keys.indexOf(key);if(a<0||b<0)return;keys.splice(a,1);keys.splice(b,0,from);emit('update:modelValue',keys)}
</script>
<template>
 <div class="field-selection-grid">
  <section class="available-fields"><header><h3>{{t('可选字段')}}</h3><span>{{fields.length}}</span></header><input v-model="query" type="search" :aria-label="t('搜索字段名称或标识')" :placeholder="t('搜索字段名称或标识')" :disabled="disabled"><div class="field-scroll"><section v-for="group in groups" :key="group.name" class="field-group"><h4>{{t(group.name)}}</h4><label v-for="field in group.fields" :key="field.key"><input type="checkbox" :checked="selected.some(item=>item.key===field.key)" :disabled="disabled||field.fixed" @change="change(field.key,($event.target as HTMLInputElement).checked)"><span>{{label(field)}}</span><small v-if="field.fixed">{{t('固定')}}</small></label></section><p v-if="!groups.length">{{t('没有匹配的字段')}}</p></div></section>
  <section class="chosen-fields"><header><h3>{{t('已选字段')}}</h3><span>{{selected.length}}</span></header><p class="field-selection-help">{{t(sortable?'拖拽调整顺序，也可使用上移、下移按钮或 Alt + 方向键。':'仅控制显示与隐藏；详情按页面原有分组顺序展示。')}}</p><ol class="field-scroll"><li v-for="(field,index) in selected" :key="field.key" :draggable="sortable&&!disabled&&!field.fixed" :class="{dragging:dragging===field.key}" :tabindex="sortable?0:undefined" @dragstart="start(field,$event)" @dragend="dragging=''" @dragover.prevent @drop.prevent="drop(field.key)" @keydown.alt.up.prevent="move(field.key,-1)" @keydown.alt.down.prevent="move(field.key,1)"><span class="field-order">{{index+1}}</span><span class="chosen-label">{{label(field)}}<small>{{t(category(field))}}</small></span><span v-if="field.fixed" class="fixed-hint">{{t('固定')}}</span><div v-else class="field-controls"><template v-if="sortable"><button type="button" :disabled="disabled||index===0||selected[index-1]?.fixed" :aria-label="t('上移字段')+' '+label(field)" @click="move(field.key,-1)">↑</button><button type="button" :disabled="disabled||index===selected.length-1" :aria-label="t('下移字段')+' '+label(field)" @click="move(field.key,1)">↓</button></template><button type="button" :disabled="disabled" :aria-label="t('移除字段 {name}',{name:label(field)})" @click="change(field.key,false)">×</button></div></li><li v-if="!selected.length" class="empty-fields">{{t('尚未选择字段')}}</li></ol></section>
 </div>
</template>
<style scoped>
.field-selection-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);min-height:0;flex:1;border-block:1px solid var(--line);color:var(--ink)}.field-selection-grid>section{min-width:0;display:flex;flex-direction:column;padding:16px;min-height:0}.available-fields{border-right:1px solid var(--line)}.field-selection-grid header{display:flex;align-items:center;gap:8px;margin-bottom:12px}.field-selection-grid h3{margin:0;font-size:13px}.field-selection-grid header span{font-size:11px;color:var(--muted);border:1px solid var(--line);border-radius:4px;padding:2px 6px}.available-fields>input{width:100%;min-width:0;box-sizing:border-box;padding:9px 10px;border:1px solid var(--line);border-radius:6px;background:var(--surface);color:var(--ink);font:inherit;font-size:12px;margin-bottom:10px}.field-scroll{overflow:auto;min-height:0;flex:1;margin:0;padding:0;list-style:none;max-height:48vh}.field-group h4{font-size:11px;color:var(--muted);margin:12px 0 6px}.field-group label{display:flex!important;align-items:center;gap:8px;padding:8px 4px;font-size:12px;min-width:0;cursor:pointer}.field-group input{width:15px!important;height:15px;flex:none;accent-color:var(--primary);margin:0}.field-group span{min-width:0;overflow-wrap:anywhere}.field-group small{margin-left:auto;color:var(--muted);font-size:10px;flex:none}.field-selection-help{font-size:11px;line-height:1.7;color:var(--muted);margin:0 0 11px}.chosen-fields li{display:flex;align-items:center;gap:8px;border:1px solid var(--line);border-radius:6px;padding:8px;margin-bottom:7px;background:var(--surface);min-height:40px}.chosen-fields li[draggable=true]{cursor:grab}.chosen-fields li.dragging{opacity:.45}.chosen-label{flex:1;min-width:0;overflow-wrap:anywhere;font-size:12px}.chosen-label small{display:block;color:var(--muted);font-size:10px;margin-top:3px}.field-order,.fixed-hint{font-size:10px;color:var(--muted);flex:none}.field-controls{display:flex;gap:3px;flex:none}.field-controls button{border:1px solid var(--line);background:var(--surface);color:var(--muted);border-radius:4px;width:25px;height:28px;font:inherit;cursor:pointer}.field-controls button:disabled{opacity:.3;cursor:not-allowed}.field-controls button:focus-visible,.chosen-fields li:focus-visible{outline:2px solid var(--primary);outline-offset:2px}.empty-fields{font-size:12px;color:var(--muted)}@media(max-width:700px){.field-selection-grid{grid-template-columns:minmax(0,1fr)}.available-fields{border-right:0;border-bottom:1px solid var(--line)}.field-scroll{max-height:25vh}.field-selection-grid>section{padding:12px}.field-group label{min-height:38px}.available-fields>input{font-size:16px}.field-controls button{min-width:34px;min-height:38px}.field-controls{gap:4px}}
</style>
