<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { onBeforeRouteLeave, onBeforeRouteUpdate } from 'vue-router'
import { t, formatDate } from '../i18n'
import { departmentPath, permits, type Department, type OrganizationContext, type ProjectMembership } from '../organization'
import { useSettingsScope } from './settingsScope'
import OrganizationModal from './OrganizationModal.vue'
import { Button } from './ui/button'
const props=defineProps<{context:OrganizationContext;section:string}>(),emit=defineEmits<{(event:'changed'):void}>(),scope=useSettingsScope()
const items=ref<any[]>([]),departments=ref<Department[]>([]),loading=ref(false),saving=ref(false),error=ref(''),notice=ref(''),status=ref('pending')
const opened=ref(false),createdLink=ref(''),review=ref<any>(null),decision=ref<'approve'|'reject'>('approve'),reviewConfirmed=ref(false)
const form=reactive({name:'',expiresInHours:168,maxUses:50,departmentIds:[] as string[],allowedRoles:[] as string[]})
const approval=reactive({email:'',initialPassword:'',employeeNo:'',projectMemberships:[] as ProjectMembership[],reason:''})
const allowed=computed(()=>permits(props.context,props.section==='invitations'?'invitations.manage':'applications.review'))
const message=(cause:unknown)=>cause instanceof Error?cause.message:'操作失败，请稍后重试'
const dirty=computed(()=>opened.value||!!review.value)
let projectLeaveApproved=false
async function load(){if(!allowed.value)return;loading.value=true;error.value='';try{const [data,directory]=await Promise.all([scope.request<{items:any[]}>('/organization/'+(props.section==='invitations'?'invitations':'applications?status='+encodeURIComponent(status.value))),scope.request<{items:Department[]}>('/organization/departments')]);items.value=data.items;departments.value=directory.items}catch(cause){error.value=message(cause)}finally{loading.value=false}}
function createDialog(){Object.assign(form,{name:'',expiresInHours:168,maxUses:50,departmentIds:[],allowedRoles:[]});error.value='';opened.value=true}
function close(){if(saving.value)return;if(!window.confirm(t('放弃尚未保存的设置修改？')))return;opened.value=false;review.value=null;approval.initialPassword=''}
async function create(){if(saving.value||!allowed.value)return;saving.value=true;error.value='';try{const result=await scope.request<{url:string}>('/organization/invitations',{method:'POST',body:JSON.stringify(form)});if(!/^\/join\/[A-Za-z0-9_-]+$/.test(result.url))throw Error('邀请链接格式不正确');createdLink.value=location.origin+result.url;opened.value=false;await load();emit('changed')}catch(cause){error.value=message(cause)}finally{saving.value=false}}
async function copyLink(){try{await navigator.clipboard.writeText(createdLink.value);notice.value='邀请链接已复制'}catch{notice.value='请选中下方链接，手动复制'}}
async function revoke(item:any){if(saving.value||!window.confirm(t('撤销后此邀请链接立即失效，确定撤销？')))return;saving.value=true;error.value='';try{await scope.request('/organization/invitations/'+item.id+'/revoke',{method:'POST',body:'{}'});createdLink.value='';await load();notice.value='邀请链接已撤销'}catch(cause){error.value=message(cause)}finally{saving.value=false}}
function startReview(item:any,value:'approve'|'reject'){review.value=item;decision.value=value;reviewConfirmed.value=false;Object.assign(approval,{email:'',initialPassword:'',employeeNo:'',projectMemberships:[],reason:''});error.value=''}
async function submitReview(){if(saving.value||!review.value||!allowed.value||decision.value==='approve'&&!reviewConfirmed.value)return;saving.value=true;error.value='';try{await scope.request('/organization/applications/'+review.value.id+'/'+decision.value,{method:'POST',body:JSON.stringify(decision.value==='approve'?{email:approval.email,initialPassword:approval.initialPassword,employeeNo:approval.employeeNo,projectMemberships:approval.projectMemberships}:{reason:approval.reason})});review.value=null;approval.initialPassword='';notice.value=decision.value==='approve'?'申请已通过，账号已激活':'申请已拒绝，未创建账号';await load();emit('changed')}catch(cause){error.value=message(cause)}finally{saving.value=false}}
function departmentName(id:string){return departments.value.find(item=>item.id===id)?.name||id||'—'}
function roleName(key:string){return props.context.roles.find(item=>item.key===key)?.name||key}
function usable(item:any){return !item.revokedAt&&item.status!=='revoked'&&new Date(item.expiresAt).getTime()>Date.now()&&item.uses<item.maxUses}
function beforeUnload(event:BeforeUnloadEvent){const switching=projectLeaveApproved&&(localStorage.getItem('devflow-project')||'prj_orbit')!==scope.project;if(!switching&&(dirty.value||saving.value)){event.preventDefault();event.returnValue=''}}
function canLeave(){return !saving.value&&(projectLeaveApproved||!dirty.value||window.confirm(t('放弃尚未保存的设置修改？')))}
function beforeProjectChange(event:Event){projectLeaveApproved=false;if(!canLeave())event.preventDefault();else projectLeaveApproved=true}
function cancelProjectLeave(){projectLeaveApproved=false}
onBeforeRouteLeave(canLeave);onBeforeRouteUpdate(canLeave)
onMounted(()=>{void load();window.addEventListener('beforeunload',beforeUnload);window.addEventListener('devflow-before-project-change',beforeProjectChange);window.addEventListener('devflow-project-change-cancelled',cancelProjectLeave)})
onBeforeUnmount(()=>{approval.initialPassword='';createdLink.value='';window.removeEventListener('beforeunload',beforeUnload);window.removeEventListener('devflow-before-project-change',beforeProjectChange);window.removeEventListener('devflow-project-change-cancelled',cancelProjectLeave)})
</script>
<template>
  <section v-if="allowed" class="org-access-list" :class="{'org-applications':section!=='invitations'}" :aria-busy="loading||saving">
    <div class="org-tools org-access-toolbar">
      <p class="org-note">{{t(section==='invitations'?'链接只允许提交加入申请，不直接开放组织访问权限。':'申请角色仅作参考，管理员需明确授予实际项目角色。')}}</p>
      <Button v-if="section==='invitations'" :disabled="saving||loading" @click="createDialog">＋ {{t('创建邀请链接')}}</Button>
      <label v-else class="org-status-filter"><span>{{t('审批状态')}}</span><select v-model="status" :aria-label="t('审批状态')" :disabled="loading||saving" @change="load"><option value="pending">{{t('待审批')}}</option><option value="approved">{{t('已通过')}}</option><option value="rejected">{{t('已拒绝')}}</option></select></label>
    </div>
    <p v-if="error&&!opened&&!review" class="org-error" role="alert">{{t(error)}}</p><p v-if="notice" class="org-success" role="status">{{t(notice)}}</p>
    <div v-if="createdLink" class="org-created-link"><b>{{t('邀请链接已生成')}}</b><p>{{t('链接仅在创建后显示一次，请复制后发给需要加入的成员。')}}</p><div class="org-actions"><input :value="createdLink" readonly :aria-label="t('邀请链接')" @focus="($event.target as HTMLInputElement).select()"><Button @click="copyLink">{{t('复制链接')}}</Button></div><small>{{t('当前为本地运行，其他设备无法通过 127.0.0.1 访问。')}}</small></div>
    <div class="org-table-wrap" role="region" :aria-label="t(section==='invitations'?'邀请链接':'加入申请')" tabindex="0">
      <table class="org-table org-access-table" :class="{'has-records':!loading&&items.length>0}">
        <thead><tr v-if="section==='invitations'"><th scope="col">{{t('链接名称')}}</th><th scope="col">{{t('有效期至')}}</th><th scope="col">{{t('已用 / 上限')}}</th><th scope="col">{{t('状态')}}</th><th scope="col">{{t('操作')}}</th></tr><tr v-else><th scope="col">{{t('申请人')}}</th><th scope="col">{{t('部门')}}</th><th scope="col">{{t('申请角色')}}</th><th scope="col">{{t('申请时间')}}</th><th scope="col">{{t('状态')}}</th><th scope="col">{{t('操作')}}</th></tr></thead>
        <tbody>
          <tr v-if="loading"><td :colspan="section==='invitations'?5:6" class="org-empty">{{t('正在加载…')}}</td></tr>
          <tr v-else-if="!items.length"><td :colspan="section==='invitations'?5:6" class="org-empty">{{t('暂无符合条件的记录')}}</td></tr>
          <template v-else><tr v-for="item in items" :key="item.id">
            <template v-if="section==='invitations'"><td><b>{{item.name}}</b><small>{{item.id}}</small></td><td>{{formatDate(item.expiresAt)}}</td><td>{{item.uses}} / {{item.maxUses}}</td><td><span class="org-pill" :class="{active:usable(item)}">{{t(usable(item)?'有效':'已失效')}}</span></td><td><Button v-if="!item.revokedAt&&item.status!=='revoked'" variant="ghost" size="sm" :disabled="saving" @click="revoke(item)">{{t('撤销')}}</Button></td></template>
            <template v-else><td><b>{{item.name}}</b></td><td>{{departmentName(item.departmentId)}}</td><td>{{t(roleName(item.requestedRole))}}</td><td>{{formatDate(item.createdAt)}}</td><td><span class="org-pill" :class="item.status==='pending'?'pending':item.status==='approved'?'active':''">{{t(item.status==='pending'?'待审批':item.status==='approved'?'已通过':'已拒绝')}}</span></td><td><div v-if="item.status==='pending'" class="org-actions"><Button variant="outline" size="sm" :disabled="saving" @click="startReview(item,'approve')">{{t('审核并激活')}}</Button><Button variant="ghost" size="sm" :disabled="saving" @click="startReview(item,'reject')">{{t('拒绝')}}</Button></div><small v-else>{{item.reason||'—'}}</small></td></template>
          </tr></template>
        </tbody>
      </table>
    </div>
    <OrganizationModal v-if="opened" :title="t('创建邀请链接')" :busy="saving" @close="close"><form id="org-invite-form" class="org-form" :inert="saving" @submit.prevent="create"><label>{{t('链接名称')}} *<input v-model="form.name" required maxlength="80" :placeholder="t('例如：研发团队入职邀请')"></label><div class="org-form-two"><label>{{t('有效小时数')}}<input v-model.number="form.expiresInHours" type="number" min="1" max="720" required></label><label>{{t('最多申请人数')}}<input v-model.number="form.maxUses" type="number" min="1" max="500" required></label></div><fieldset><legend>{{t('可申请部门')}}</legend><div class="org-multi"><label v-for="item in departments.filter(item=>item.status==='active')" :key="item.id" class="org-check"><input v-model="form.departmentIds" type="checkbox" :value="item.id">{{departmentPath(item,departments)}}</label></div><small>{{t('请至少选择一个部门')}}</small></fieldset><fieldset><legend>{{t('可申请角色')}}</legend><label v-for="role in context.roles.filter(role=>role.key!=='project_admin')" :key="role.key" class="org-check"><input v-model="form.allowedRoles" type="checkbox" :value="role.key">{{t(role.name)}}</label><small>{{t('邀请链接不可申请管理员权限')}}</small></fieldset><p v-if="error" class="org-error" role="alert">{{t(error)}}</p></form><template #footer><Button variant="outline" :disabled="saving" @click="close">{{t('取消')}}</Button><Button form="org-invite-form" type="submit" :disabled="saving||!form.departmentIds.length||!form.allowedRoles.length">{{t('生成链接')}}</Button></template></OrganizationModal>
    <OrganizationModal v-if="review" :title="t(decision==='approve'?'审核并激活':'拒绝申请')" :busy="saving" wide @close="close"><form id="org-review-form" class="org-form" :inert="saving" @submit.prevent="submitReview"><div class="org-review-summary"><b>{{review.name}}</b><span>{{departmentName(review.departmentId)}} · {{t(roleName(review.requestedRole))}}</span></div><template v-if="decision==='approve'"><p class="org-note">{{t('请核实申请人身份。以下实际权限由管理员配置，不会自动采用申请角色。')}}</p><div class="org-form-two"><label>{{t('登录邮箱')}} *<input v-model="approval.email" type="email" required maxlength="254" autocomplete="off"></label><label>{{t('初始密码')}} *<input v-model="approval.initialPassword" type="password" :required="!context.initialPasswordConfigured" minlength="6" maxlength="72" autocomplete="new-password"><small v-if="context.initialPasswordConfigured">{{t('留空使用系统初始密码，首次登录后必须修改。')}}</small></label></div><label>{{t('工号')}}<input v-model="approval.employeeNo" maxlength="80"></label><fieldset><legend>{{t('实际项目权限')}}</legend><div v-for="(membership,index) in approval.projectMemberships" :key="index" class="org-project-role"><select v-model="membership.projectId" :aria-label="t('项目空间')" required><option value="">{{t('选择项目')}}</option><option v-for="project in context.projects.filter(project=>project.status==='active')" :key="project.id" :value="project.id" :disabled="approval.projectMemberships.some((item,i)=>i!==index&&item.projectId===project.id)">{{project.name}}</option></select><select v-model="membership.role" :aria-label="t('实际项目角色')" required><option value="">{{t('选择角色')}}</option><option v-for="role in context.roles.filter(role=>context.isTenantAdmin||role.key!=='project_admin')" :key="role.key" :value="role.key">{{t(role.name)}}</option></select><button type="button" :aria-label="t('移除项目权限')" @click="approval.projectMemberships.splice(index,1)">×</button></div><Button variant="outline" type="button" size="sm" @click="approval.projectMemberships.push({projectId:'',role:''})">＋ {{t('添加项目权限')}}</Button></fieldset><label class="org-check"><input v-model="reviewConfirmed" type="checkbox" required>{{t('已核实身份和权限，同意激活此账号')}}</label><small>{{t('请通过可信渠道将登录邮箱和初始密码告知本人。')}}</small></template><label v-else>{{t('拒绝原因')}}<textarea v-model="approval.reason" required maxlength="500"></textarea><small>{{t('拒绝后不会创建账号，申请人可联系管理员重新申请。')}}</small></label><p v-if="error" class="org-error" role="alert">{{t(error)}}</p></form><template #footer><Button variant="outline" :disabled="saving" @click="close">{{t('取消')}}</Button><Button :variant="decision==='reject'?'destructive':'default'" form="org-review-form" type="submit" :disabled="saving||decision==='approve'&&(!reviewConfirmed||!approval.projectMemberships.length)">{{t(decision==='approve'?'通过并激活':'确认拒绝')}}</Button></template></OrganizationModal>
  </section><p v-else class="org-error" role="alert">{{t('你没有此管理功能的权限')}}</p>
</template>
<style scoped>
.org-access-list{min-width:0;max-width:100%}.org-access-toolbar{justify-content:flex-start;align-items:center;gap:12px;margin-bottom:14px}.org-access-toolbar>.org-note{flex:1 1 360px;min-width:0;margin:0;line-height:1.6;overflow-wrap:anywhere}.org-status-filter{display:flex;align-items:center;gap:8px;flex:none;font-size:var(--ui-font-caption);color:var(--muted-foreground)}.org-status-filter>span{white-space:nowrap}.org-status-filter select{min-width:112px;max-width:100%;width:auto}.org-access-list>.org-table-wrap{max-width:100%;border-radius:var(--ui-control-radius);background:var(--card);scrollbar-gutter:auto}.org-access-table{table-layout:fixed;white-space:normal}.org-access-table th{padding:10px 12px;font-weight:500;white-space:nowrap}.org-access-table td{padding:12px;overflow-wrap:anywhere;line-height:1.6}.org-access-table .org-empty{padding:36px 16px}.org-access-table.has-records{min-width:700px}.org-applications .org-access-table.has-records{min-width:780px}.org-access-table .org-actions{gap:6px}.org-access-table .org-pill{white-space:nowrap}.org-access-table td>small{overflow-wrap:anywhere}.org-applications .org-access-table.has-records th:nth-child(4){width:160px}.org-applications .org-access-table.has-records th:nth-child(5){width:86px}.org-applications .org-access-table.has-records th:nth-child(6){width:184px}
.org-created-link{border:1px solid #10b98144;background:#10b98108;border-radius:10px;padding:18px;margin-bottom:20px}.org-created-link>b{font-size:14px}.org-created-link p,.org-created-link small{font-size:11px;color:var(--muted);line-height:1.8}.org-created-link input{flex:1;min-width:180px}.org-created-link>small{display:block;margin-top:8px}.org-review-summary{display:flex;gap:14px;align-items:center;border:1px solid var(--line);padding:14px;border-radius:8px}.org-review-summary>span{font-size:12px;color:var(--muted)}
</style>

<style scoped>
@media(max-width:820px){
 .org-access-toolbar{gap:10px}.org-access-toolbar>.org-note{flex-basis:100%}.org-status-filter{width:100%;justify-content:space-between}.org-status-filter select{width:160px;max-width:calc(100% - 80px)}.org-access-table:not(.has-records) th{padding:10px 4px;font-size:var(--ui-font-caption);white-space:normal;overflow-wrap:anywhere}.org-access-table .org-empty{padding:28px 12px}
 .org-created-link{padding:15px;min-width:0}.org-created-link .org-actions{flex-wrap:wrap}.org-created-link input{min-width:0;width:100%;flex-basis:100%}.org-created-link p,.org-created-link small{overflow-wrap:anywhere}.org-review-summary{flex-wrap:wrap;gap:10px}.org-review-summary>*{min-width:0;overflow-wrap:anywhere}
}
</style>
