<script setup lang="ts">
import { t } from '../i18n'
import { computed, ref, useId, watch } from 'vue'
import MemberMultiSelect from './MemberMultiSelect.vue'
import { normalizeRoleWeights, roleWeightDefinitions, weightQuickValues, weightTotal, type RequirementMember, type RoleWeightKey, type RoleWeights } from '../requirementFields'
const props = defineProps<{ modelValue: RoleWeights | undefined; members: RequirementMember[]; disabled?: boolean; readonly?: boolean; currentUserId?: string; compact?: boolean }>()
const emit = defineEmits<{ (event: 'update:modelValue', value: RoleWeights): void }>()
const values = computed(() => normalizeRoleWeights(props.modelValue))
const total = computed(() => weightTotal(values.value))
const filled = computed(() => roleWeightDefinitions.filter(({ key }) => values.value[key].value !== null).length)
const quickRole=ref<RoleWeightKey|null>(null), quickId='weight-quick-'+useId()
const editable=computed(()=>!props.disabled&&!props.readonly)
watch(editable,value=>{if(!value)quickRole.value=null})
function openQuick(key:RoleWeightKey){if(editable.value)quickRole.value=key}
function hoverQuick(key:RoleWeightKey,event:PointerEvent){if(event.pointerType==='mouse')openQuick(key)}
function leaveQuick(key:RoleWeightKey,event:MouseEvent){if(quickRole.value===key&&!(event.currentTarget as HTMLElement).contains(document.activeElement))quickRole.value=null}
function blurQuick(key:RoleWeightKey,event:FocusEvent){if(quickRole.value===key&&!(event.currentTarget as HTMLElement).contains(event.relatedTarget as Node|null))quickRole.value=null}
function escapeQuick(event:KeyboardEvent){if(quickRole.value){event.preventDefault();event.stopPropagation();quickRole.value=null}}
function applyQuick(key:RoleWeightKey,value:number){if(!editable.value||!(weightQuickValues as readonly number[]).includes(value))return;emit('update:modelValue',{...values.value,[key]:{...values.value[key],value}})}
function selectedName(key: RoleWeightKey) { const userIds = values.value[key].userIds!; return userIds.length ? userIds.map(id => props.members.find(member => member.id === id)?.name || t('原绑定成员（不可用）')).join('、') : t('未绑定') }
function setMembers(key: RoleWeightKey, userIds: string[]) { if(!editable.value)return;emit('update:modelValue', { ...values.value, [key]: { ...values.value[key], userId:userIds[0] || '', userIds } }) }
function setValue(key: RoleWeightKey, event: Event) { if(!editable.value)return;const input = event.target as HTMLInputElement; const value = input.value === '' ? null : Number(input.value); emit('update:modelValue', { ...values.value, [key]: { ...values.value[key], value } }) }
</script>
<template>
  <section class="requirement-weights" :class="{'weights-compact':compact}" :aria-label="t('需求权重')">
    <div class="weight-table-head" aria-hidden="true"><span>{{ t('职能 / 难度') }}</span><span>{{ t('绑定人员') }}</span><span>{{ t('权重数值') }}</span></div>
    <div v-for="row in roleWeightDefinitions" :key="row.key" class="weight-row">
      <span class="weight-label">{{ t(row.label) }}<small>{{ t(row.memberLabel) }}</small></span>
      <span v-if="readonly" class="weight-member">{{ selectedName(row.key) }}</span>
      <MemberMultiSelect v-else :compact="compact" :model-value="values[row.key].userIds!" :members="members" :member-roles="row.roles" :label="t('{role}权重绑定',{role:t(row.memberLabel)})" :current-user-id="currentUserId" :disabled="disabled" :show-lead="false" :hint="t('同一职能可绑定多人，难度数值只计算一次。')" @update:modelValue="setMembers(row.key,$event)"/>
      <span v-if="readonly" class="weight-value">{{ values[row.key].value ?? '—' }}</span><div v-else class="weight-value-control" @pointerenter="hoverQuick(row.key,$event)" @pointerleave="leaveQuick(row.key,$event)" @focusout="blurQuick(row.key,$event)" @keydown.esc="escapeQuick"><div class="weight-number-entry"><input type="number" min="0" max="1000000" step="any" inputmode="decimal" :placeholder="t('未评估')" :aria-label="t('{field}权重',{field:t(row.label)})" :aria-describedby="quickRole===row.key?quickId+'-'+row.key+'-hint':undefined" :value="values[row.key].value ?? ''" :disabled="disabled" @focus="openQuick(row.key)" @input="setValue(row.key, $event)"><button type="button" class="weight-quick-trigger" :disabled="disabled" :aria-label="t('选择{field}快捷数值',{field:t(row.label)})" :aria-expanded="quickRole===row.key&&editable" :aria-controls="quickId+'-'+row.key" @click="openQuick(row.key)">⋯</button></div><div v-if="quickRole===row.key&&editable" :id="quickId+'-'+row.key" class="weight-quick-popover"><div class="weight-quick-panel" role="group" :aria-label="t('{field}快捷数值',{field:t(row.label)})"><b>{{t('快捷数值')}}</b><div class="weight-quick-options"><button v-for="value in weightQuickValues" :key="value" type="button" :aria-pressed="values[row.key].value===value" :class="{selected:values[row.key].value===value}" :aria-label="t('将{field}设为{value}',{field:t(row.label),value})" @click="applyQuick(row.key,value)">{{value}}</button></div><small :id="quickId+'-'+row.key+'-hint'">{{t('仅更新当前难度，点击页面保存后生效。')}}</small></div></div></div>
    </div>
    <footer class="weight-total"><div><b>{{ t('权重总和') }}</b><small>{{ t('五项难度直接相加，未填写项按 0 计') }}</small></div><span>{{ t('{count} / 5 已评估',{count:filled}) }}</span><output :aria-label="t('权重总和')">{{ total }}</output></footer>
  </section>
</template>
<style scoped>
/* 侧栏把同一职能的人员和难度放在同一组，保持宽表模式兼容详情和模板。 */
.weights-compact{min-width:0;max-width:100%}.weights-compact .weight-table-head{display:none}.weights-compact .weight-row{display:grid;grid-template-columns:minmax(0,1fr) minmax(88px,112px);gap:8px;padding:12px 0;border-bottom:1px solid var(--border)}.weights-compact .weight-label{grid-column:1;grid-row:1;align-self:center;min-width:0}.weights-compact .weight-label small{display:none}.weights-compact .weight-value-control,.weights-compact .weight-value{grid-column:2;grid-row:1;min-width:0}.weights-compact .weight-row :deep(.member-multi),.weights-compact .weight-member{grid-column:1/-1;grid-row:2;min-width:0}.weights-compact .weight-total{display:flex;flex-wrap:wrap;gap:8px;padding:12px 0}.weights-compact .weight-total>div{flex:1 1 100%}.weights-compact .weight-total output{margin-left:auto}.weights-compact .weight-quick-popover{max-width:min(280px,calc(100vw - 64px));right:0;left:auto}
.weight-value-control{position:relative;min-width:0}.weight-number-entry{display:flex;align-items:stretch;gap:4px}.weight-number-entry input{flex:1;min-width:0}.weight-quick-trigger{flex:none;width:25px;border:1px solid #dfe3eb;border-radius:6px;background:#fafaff;color:#625de0;font-size:17px;line-height:1;padding:0;cursor:pointer}.weight-quick-trigger:disabled{opacity:.4;cursor:not-allowed}.weight-quick-trigger:focus-visible,.weight-quick-options button:focus-visible{outline:2px solid #7771ed;outline-offset:2px}.weight-quick-popover{position:absolute;right:0;top:100%;padding-top:7px;width:264px;max-width:calc(100vw - 48px);z-index:90}.weight-quick-panel{border:1px solid #dfe2f1;border-radius:9px;background:#fff;padding:12px;box-shadow:0 10px 30px #24325521}.weight-quick-panel>b{display:block;margin-bottom:9px;font-size:11px;color:#667085}.weight-quick-options{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px}.weight-quick-options button{min-height:30px;padding:5px 1px;border:1px solid #e4e7ef;border-radius:5px;background:#fafbfe;color:#475467;font-size:12px;font-variant-numeric:tabular-nums;cursor:pointer}.weight-quick-options button:hover,.weight-quick-options button.selected{border-color:#8f89ef;color:#514cc7;background:#efedff}.weight-quick-panel>small{display:block;margin-top:9px;font-size:10px;line-height:1.6;color:#98a2b3}
.requirement-weights{overflow:visible!important}.weight-table-head{border-radius:8px 8px 0 0}.weight-total{border-radius:0 0 8px 8px}.weight-row{align-items:start!important}.weight-label,.weight-row>.weight-value{padding-top:8px}
.requirement-weights{border:1px solid #e4e7ec;border-radius:8px;overflow:hidden;background:#fff;width:100%;min-width:0}.weight-table-head,.weight-row{display:grid;grid-template-columns:minmax(115px,1.1fr) minmax(110px,1fr) minmax(90px,.7fr);align-items:center;gap:12px;padding:10px 14px}.weight-table-head{background:#f8f9fc;color:#667085;font-size:11px}.weight-row{border-top:1px solid #eef0f4}.weight-label{color:#344054;font-size:12px;font-weight:550}.weight-label small{display:block;margin-top:3px;color:#98a2b3;font-size:10px;font-weight:400}.weight-row select,.weight-row input{width:100%;min-width:0;margin:0;padding:8px 9px;border:1px solid #dfe3eb;border-radius:6px;background:#fff;font-size:12px;color:#344054;outline:none}.weight-row input{text-align:right;font-variant-numeric:tabular-nums}.weight-row select:focus,.weight-row input:focus{border-color:#7771ed;box-shadow:0 0 0 3px #706aec18}.weight-row select:disabled,.weight-row input:disabled{background:#f9fafb;cursor:not-allowed}.weight-member{font-size:12px;color:#667085}.weight-value{text-align:right;font-size:13px;font-variant-numeric:tabular-nums}.weight-total{display:flex;align-items:center;gap:14px;padding:13px 14px;border-top:1px solid #e4e7ec;background:#f8f8ff}.weight-total div{flex:1}.weight-total b{font-size:12px;color:#344054}.weight-total small{display:block;margin-top:4px;color:#667085;font-size:10px}.weight-total>span{color:#8a8da8;font-size:10px;white-space:nowrap}.weight-total output{min-width:64px;text-align:right;font-size:24px;font-weight:650;color:#5b5ce2;font-variant-numeric:tabular-nums}@media(max-width:1180px){.weight-table-head,.weight-row{gap:8px;padding:10px;grid-template-columns:minmax(105px,1.1fr) minmax(98px,1fr) minmax(80px,.7fr)}.weight-total>span{display:none}}@media(max-width:700px){.weight-table-head{display:none}.weight-row{grid-template-columns:1fr 100px}.weight-label{grid-column:1/-1}.weight-label small{display:inline;margin-left:7px}.weight-total output{font-size:21px}}
</style>
<style scoped>
@media(max-width:820px){
 .weight-table-head{display:none}.weight-row{grid-template-columns:minmax(0,1fr);gap:12px;padding:14px}
 .weight-label{grid-column:auto}.weight-label small{white-space:normal}.weight-member{overflow-wrap:anywhere}
 .weight-value-control{width:100%}.weight-number-entry input{font-size:16px;min-height:44px}
 .weight-quick-trigger{width:44px;min-height:44px}.weight-quick-options{grid-template-columns:repeat(4,minmax(0,1fr))}.weight-quick-options button{min-height:44px}
 .weight-total{flex-wrap:wrap}.weight-total div{min-width:0}
}
</style>
