<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { onBeforeRouteLeave, onBeforeRouteUpdate } from 'vue-router'
import { t } from '../i18n'
import { savedView, viewConfig, type SavedRequirementView, type RequirementViewConfig } from '../savedViews'
import { useSettingsDialog, useSettingsScope } from './settingsScope'
import AppSelect from './AppSelect.vue'
const props=defineProps<{config:RequirementViewConfig;disabled?:boolean;showShortcuts?:boolean}>()
const emit=defineEmits<{(event:'apply',config:RequirementViewConfig):void;(event:'builtin',key:string):void}>()
const scope=useSettingsScope(),items=ref<SavedRequirementView[]>([]),loading=ref(false),saving=ref(false),error=ref(''),canCreate=ref(false),canShare=ref(false),selection=ref(''),opened=ref(false),name=ref(''),visibility=ref<'personal'|'shared'>('personal'),editing=ref<SavedRequirementView|null>(null),draft=ref<RequirementViewConfig|null>(null)
const selected=computed(()=>items.value.find(item=>String(item.id)===selection.value)),changed=computed(()=>selected.value&&JSON.stringify(props.config)!==JSON.stringify(selected.value.config))
// 选择器使用明确的来源前缀，避免用户创建了“1”等简短名称后难以分辨其归属。
// 统一交给 AppSelect 渲染，可以由 Reka 自动避让边界且限制弹层高度，不会再覆盖大面积列表。
const viewOptions=computed(()=>[
 {value:'',label:t('当前自定义筛选'),disabled:true},
 {value:'builtin:all',label:`${t('内置模板')} · ${t('全部需求')}`},
 {value:'builtin:mine',label:`${t('内置模板')} · ${t('我负责的')}`},
 {value:'builtin:review',label:`${t('内置模板')} · ${t('待评审')}`},
 {value:'builtin:release',label:`${t('内置模板')} · ${t('待上线')}`},
 ...items.value.filter(item=>item.scope==='personal').map(item=>({value:String(item.id),label:`${t('个人视图')} · ${item.name}`})),
 ...items.value.filter(item=>item.scope==='shared').map(item=>({value:String(item.id),label:`${t('项目共享视图')} · ${item.name}`})),
])
let sequence=0,disposed=false,projectLeaveApproved=false
function current(version:number){return !disposed&&version===sequence&&scope.current()}
async function load(){if(saving.value||opened.value||disposed||!scope.current())return;const version=++sequence;loading.value=true;error.value='';try{const result=await scope.request<any>('/requirement-views');if(!current(version))return;if(!Array.isArray(result.items)||typeof result.canCreate!=='boolean'||typeof result.canShare!=='boolean')throw Error('保存视图数据格式不正确，请重试');items.value=result.items.map(savedView);canCreate.value=result.canCreate;canShare.value=result.canShare;if(selection.value&&!selection.value.startsWith('builtin:')&&!items.value.some(item=>String(item.id)===selection.value))selection.value=''}catch(cause){if(current(version))error.value=cause instanceof Error?cause.message:'视图载入失败，请重试'}finally{if(current(version))loading.value=false}}
function apply(value:string){if(props.disabled||saving.value||!scope.current())return;if(value.startsWith('builtin:')){selection.value=value;emit('builtin',value.slice(8));return}const item=items.value.find(item=>String(item.id)===value);if(!item)return;selection.value=value;emit('apply',viewConfig(item.config))}
function begin(update=false){if(!canCreate.value||props.disabled||saving.value||loading.value||!scope.current()||update&&!selected.value?.canManage)return;error.value='';try{draft.value=viewConfig(props.config)}catch(cause){error.value=(cause as Error).message;return};editing.value=update?selected.value!:null;name.value=update?selected.value!.name:'';visibility.value=update?selected.value!.scope:'personal';opened.value=true}
function close(){if(!saving.value){opened.value=false;draft.value=null;editing.value=null;name.value=''}}
async function save(){if(saving.value||!opened.value||!draft.value||!canCreate.value||!scope.current())return;const title=name.value.trim();if(!title||Array.from(title).length>30||/[\u0000-\u001f\u007f]/.test(title)){error.value='视图名称需为 1–30 个字符';return}if(visibility.value==='shared'&&!canShare.value){error.value='仅管理员可执行此操作';return}const version=++sequence,target=editing.value?{...editing.value}:null,payload=target?{name:title,version:target.version,config:viewConfig(draft.value)}:{name:title,scope:visibility.value,config:viewConfig(draft.value)};saving.value=true;error.value='';try{const result=savedView(await scope.request<any>('/requirement-views'+(target?'/'+target.id:''),{method:target?'PATCH':'POST',body:JSON.stringify(payload)}));if(!current(version))return;if(target&&result.id!==target.id)throw Error('保存视图数据格式不正确，请重试');items.value=[...items.value.filter(item=>item.id!==result.id),result];selection.value=String(result.id);opened.value=false;draft.value=null;editing.value=null;name.value=''}catch(cause){if(current(version))error.value=cause instanceof Error?cause.message:'视图保存失败，当前草稿已保留'}finally{if(current(version))saving.value=false}}
async function remove(){const target=selected.value;if(!target?.canManage||saving.value||props.disabled||!scope.current()||!window.confirm(t('删除视图「{name}」？仅删除模板，不影响需求数据。',{name:target.name})))return;const version=++sequence;saving.value=true;error.value='';try{const result=await scope.request<any>('/requirement-views/'+target.id,{method:'DELETE',body:JSON.stringify({version:target.version})});if(!current(version))return;if(result.deleted!==true)throw Error('保存视图数据格式不正确，请重试');items.value=items.value.filter(item=>item.id!==target.id);selection.value=''}catch(cause){if(current(version))error.value=cause instanceof Error?cause.message:'视图删除失败，请重试'}finally{if(current(version))saving.value=false}}
function canLeave(){return !saving.value&&(projectLeaveApproved||!opened.value||!name.value.trim()||window.confirm(t('视图配置尚未保存，离开将放弃当前草稿，继续吗？')))}
function beforeProjectChange(event:Event){projectLeaveApproved=false;if(!canLeave())event.preventDefault();else projectLeaveApproved=true}
function cancelledProject(){projectLeaveApproved=false}
function beforeUnload(event:BeforeUnloadEvent){if(saving.value||opened.value&&name.value.trim()){event.preventDefault();event.returnValue=''}}
const dialog=useSettingsDialog(opened,close)
watch(scope.locked,locked=>{if(locked){sequence++;items.value=[];opened.value=false;draft.value=null;name.value='';loading.value=false;saving.value=false;selection.value='';canCreate.value=false;canShare.value=false}},{flush:'sync'})
onBeforeRouteLeave(canLeave);onBeforeRouteUpdate(canLeave)
onMounted(()=>{void load();window.addEventListener('devflow-before-project-change',beforeProjectChange);window.addEventListener('devflow-project-change-cancelled',cancelledProject);window.addEventListener('beforeunload',beforeUnload)})
onBeforeUnmount(()=>{disposed=true;sequence++;window.removeEventListener('devflow-before-project-change',beforeProjectChange);window.removeEventListener('devflow-project-change-cancelled',cancelledProject);window.removeEventListener('beforeunload',beforeUnload)})
</script>
<template>
 <section class="saved-views" :aria-label="t('筛选视图')"><div class="saved-views-bar"><div v-if="showShortcuts!==false" class="quick-views" :aria-label="t('常用需求视图')"><button v-for="item in [{key:'all',label:'全部'},{key:'mine',label:'我负责的'},{key:'review',label:'待评审'},{key:'release',label:'待上线'}]" :key="item.key" type="button" :disabled="loading||saving||disabled||scope.locked.value" @click="apply('builtin:'+item.key)">{{t(item.label)}}</button></div><span class="saved-view-label">{{t('视图')}}</span><AppSelect class="saved-view-select" :model-value="selection" :options="viewOptions" :label="t('选择保存的视图')" :disabled="loading||saving||disabled||scope.locked.value" @update:model-value="apply(String($event))"/><span v-if="changed" class="view-modified">{{t('已修改，未更新模板')}}</span><button v-if="canCreate" type="button" class="btn compact" :disabled="saving||loading||disabled" @click="begin()">{{t('另存为视图')}}</button><button v-if="selected?.canManage" type="button" class="link" :disabled="saving||disabled" @click="begin(true)">{{t('更新当前视图')}}</button><button v-if="selected?.canManage" type="button" class="link" :disabled="saving||disabled" @click="remove">{{t('删除视图')}}</button><button type="button" class="link view-refresh" :disabled="saving||loading||opened||scope.locked.value" @click="load">{{t('刷新')}}</button></div><p v-if="error&&!opened" class="view-error" role="alert">{{t(error)}}</p></section>
 <div v-if="opened" class="saved-view-shade" @click.self="close"><section ref="dialog" tabindex="-1" class="saved-view-dialog" role="dialog" aria-modal="true" :aria-label="t(editing?'更新当前视图':'另存为视图')"><header><h2>{{t(editing?'更新当前视图':'另存为视图')}}</h2><button type="button" :disabled="saving" :aria-label="t('关闭')" @click="close">×</button></header><div class="saved-view-form"><label>{{t('视图名称')}}<input v-model="name" :disabled="saving" :placeholder="t('例如：本周前端待上线')"></label><label>{{t('可见范围')}}<select v-model="visibility" :disabled="saving||!!editing"><option value="personal">{{t('个人视图')}}</option><option v-if="canShare||visibility==='shared'" value="shared">{{t('项目共享视图')}}</option></select></label><p>{{t('保存搜索、筛选、列顺序、排序及列表或看板模式；不会修改需求，也不会覆盖其他人的个人列偏好。')}}</p><p v-if="draft?.assigneeMode==='me'">{{t('“我负责的”在每位访问者打开视图时，使用其当前账号匹配。')}}</p><p v-if="visibility==='shared'">{{t('项目成员均可查看；仅项目或企业管理员可以更新共享视图。')}}</p><p v-if="error" class="view-error" role="alert">{{t(error)}}</p></div><footer><button type="button" class="btn" :disabled="saving" @click="close">{{t('取消')}}</button><button type="button" class="btn primary" :disabled="saving" @click="save">{{t(saving?'保存中…':'保存视图')}}</button></footer></section></div>
</template>
<style scoped>
.quick-views{display:flex;gap:4px;align-items:center;flex-wrap:wrap}.quick-views button{font:inherit;font-size:13px;min-height:32px;border:1px solid var(--line);border-radius:6px;background:var(--surface);color:var(--ink);padding:4px 9px;cursor:pointer}.quick-views button:hover:not(:disabled){background:var(--primary-soft);color:var(--primary)}.quick-views button:disabled{opacity:.5;cursor:default}
.saved-views{padding:12px 0;border-bottom:1px solid var(--line);color:var(--ink);min-width:0}.saved-views-bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.saved-view-label{font-size:12px;color:var(--muted)}.saved-views :deep(.saved-view-select){min-width:214px;max-width:min(320px,100%)}.saved-views .link{font-size:11px}.view-modified{font-size:10px;color:var(--warning,#ae741c)}.view-refresh{margin-left:auto}.saved-view-shade{position:fixed;inset:0;z-index:180;background:#17223966;display:grid;place-items:center;padding:20px}.saved-view-dialog{width:min(500px,100%);max-height:90dvh;overflow:auto;background:var(--surface);color:var(--ink);border:1px solid var(--line);border-radius:12px;box-shadow:0 20px 70px #0003}.saved-view-dialog header,.saved-view-dialog footer{display:flex;align-items:center;gap:10px;padding:18px 20px}.saved-view-dialog header h2{margin:0;font-size:17px;flex:1}.saved-view-dialog header button{background:transparent;border:0;font-size:22px;color:var(--muted)}.saved-view-form{padding:0 20px 12px}.saved-view-form label{display:grid;gap:8px;margin:12px 0;font-size:12px}.saved-view-form input,.saved-view-form select{font:inherit;padding:10px;border:1px solid var(--line);background:var(--surface);color:var(--ink);border-radius:6px;min-width:0;max-width:100%}.saved-view-form p{font-size:11px;line-height:1.8;color:var(--muted);overflow-wrap:anywhere}.view-error,.saved-view-form .view-error{font-size:12px;color:var(--danger,#b42318)}.saved-view-dialog footer{justify-content:flex-end;border-top:1px solid var(--line)}@media(max-width:700px){.saved-views-bar{gap:8px}.saved-views :deep(.saved-view-select){min-width:0;max-width:100%;flex:1;font-size:16px;min-height:40px}.saved-views button{min-height:40px}.saved-view-shade{padding:12px}.saved-view-dialog{max-height:calc(100dvh - 24px)}.saved-view-form input,.saved-view-form select{font-size:16px}.saved-view-dialog footer button{min-height:42px}.view-modified{flex-basis:100%}}
</style>
